### ISSUE TITLE
O que a lib faz?

### ISSUE THREAD

**Issue by lfreneda** [jeduardocosta/type-validator#1]
Pra que preciso de uma lib se eu posso fazer:

typeof(Class1) == typeof(Class2)

???

**Comment by jeduardocosta** [comment]
Validar é um contexto amplo, pois você pode definir regras baseadas na sua necessidade (por nome, tipo, valores, valores em sequência etc)

O exemplo que você citou seria de comparar dois tipos, algo como "TypeComparer".

**Comment by lfreneda** [comment]
Ah entendi!
Legal ter um readme explicando melhor então.
Olhei pela primeira vez e tive esse entendimento :)

**Comment by lfreneda** [comment]
<3

**Comment by jeduardocosta** [comment]
Acho que "StructureComparer" seja um nome mais adequado.
A ideia da lib é comparar (em regras de igualdade) as estruturas fornecidas (nome, tipos, valores etc)
O que acha?

**Comment by lfreneda** [comment]
Ótimo <3 

u r the guy.

Até parece que foi eu quem dei o nome.
